title: Command DB
email: naomieow@proton.me
description: >- # this means to ignore newlines until "baseurl:"
  A database and guide for all things Minecraft command and function based!
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://cmdb.naomieow.xyz/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  naomieow

# Build settings
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed

# JTD Settings
color_scheme: dark