title: Command DB
email: naomieow@proton.me
description: >- # this means to ignore newlines until "baseurl:"
  A database and guide for all things Minecraft command and function based!
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://cmdb.naomieow.xyz/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  naomieow

# Build settings
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed

# JTD Theme Settings
search_enabled: true
color_scheme: dark

# JTD Footer
last_edit_timestamp: true

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/ApolloDatapacks/worldgen-docs/"
gh_edit_branch: "gh-pages"
gh_edit_view_mode: "tree"

# JTD Callouts
callouts:
  warning:
    title: Warning
    color: red
  highlight:
    color: yellow
  note:
    title: Note
    color: purple
  important:
    title: Important
    color: blue
  new: # For minor updates maybe?
    title: New
    color: green